### ISSUE TITLE
how to create loh file for scRNA data

### ISSUE THREAD

**Issue by helianthuszhu** [akdess/CaSpER#1]
Hi, 
   CaSpER is so great when I checked using sample dataset implemented within it. I have noticed that, in terms of the file preparation, companied with the normalized expression matrix are loh, annotation and  loh.name.mapping files. I am wondering how to create loh file for my own scRNA dataset. By using   
Extract BAF command line, I could only get .baf file containing allele frequency without baf and dev value like below.  Could you please tell me how to prepare it appropriately. Thanks.
1. From well prepared scell_gbm dataset
 chr  position   alt   ref coverage       baf         dev
1      1    631278    15    24       39 0.3846154 0.115384615
3      1    631862    38    29       67 0.5671642 0.067164179
4      1    632009     9    31       40 0.2250000 0.275000000
2. From test.baf dataset using Extract BAF
1       54072436        g       T       5       30
1       54084069        g       A       11      31
1       54085788        c       T       5       24

**Comment by akdess** [comment]
Hi Helian, 
I am very sorry for the late reply. We have updated the user manual: http://rpubs.com/akdess/472217

You can use the following command to read BAFExtract output (**path** parameter is the location of the folder that contains the BAFExtract outputs). 
loh <- readBAFExtractOutput ( path=path, sequencing.type="bulk")

loh data.frame should contain all the necessary columns.
