### ISSUE TITLE
Main Ensembl Internal Server Error

### ISSUE THREAD

**Issue by pblaney** [akdess/CaSpER#10]
Hi Akdes,

Really liked the paper and am excited to put CaSpER to use!
When using the generateAnnotation() function, I received an Internal Server Error (HTTP 500) after multiple tries as Ensembl's main server was likely just overloaded. After some troubleshooting, I managed to circumvent the issue and speed up the call by making a slight change to the function by adding a specific host to the useEnsembl() portion of the mart variable.
<img width="631" alt="image" src="https://user-images.githubusercontent.com/55849979/73786134-afce7180-4766-11ea-9274-4eff964bfe6a.png">

A suggestion I had was to include this as a mutable parameter of the generateAnnotation() function with the default being "www.ensembl.org".

Best,
Patrick

**Comment by akdess** [comment]
Thanks a lot @pblaney for the advice! We will update the code accordingly.
