### ISSUE TITLE
HMM segmentation error

### ISSUE THREAD

**Issue by AmandaKedaigle** [akdess/CaSpER#11]
Hello,
I'm getting an issue that appears to be related to recent commit. 

`> final.objects <- runCaSpER(object, removeCentromere=T, cytoband=cytoband, method="iterative")`
`Performing recursive median filtering...`
`Performing HMM segmentation...`
`Error in (function (classes, fdef, mtable)  :`
  `unable to find an inherited method for function 'space' for signature '"data.frame"'`

When I looked into the code, the error comes from the HMMsegment function. It looks like that function is expecting a RangedData object, but it is currently recieving rdata, a data.frame. This happens even with the example meningioma data.

Thanks!

**Comment by akdess** [comment]
Hi @AmandaKedaigle, thanks for letting us know. I have changed the code to the previous version.  RangedData is deprecated in R.3.6. Casper runs in R version 3.4  right now.  We will update the code in the future to make it compatible with the newest R.
