### ISSUE TITLE
Error running runCaSpER: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by BilyanaStoilova** [akdess/CaSpER#14]
Hi,
I created a casper object from 10X data using:
object <- CreateCasperObject(raw.data=sample.matrix, loh.name.mapping=loh.name.mapping, sequencing.type="single-cell", cnv.scale=3, loh.scale=3, matrix.type="normalized", expr.cutoff=4.5, log.transformed = F, annotation=annotation, method="iterative", loh=loh, filter="median",  control.sample.ids=control.sample.ids, cytoband=cytoband, genomeVersion = "hg38")
But then when I tried running 
final.objects <- runCaSpER(object, removeCentromere=T, cytoband=cytoband, method="iterative")
I got an error message:
Performing recursive median filtering...
Error: $ operator is invalid for atomic vectors
I am not sure where this error comes from, I assume it doesn't like the format of some of my objects but I can not work out which one. I suspect it might be the loh file because when I tried running 
loh <- readBAFExtractOutput(path="./BAF", sequencing.type="bulk")
I got an error:
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file './BAF/NA': No such file or directory
So I had to load the loh using:
loh <- read.table(file = "BAF/sample.baf", sep = "\t", header = FALSE, stringsAsFactors = FALSE)
which worked fine for the CreateCasperObject above.
Could you please help me solve this issue?
Thank you very much,
Bilyana

**Comment by iS4i4S** [comment]
@BilyanaStoilova 
Hi, I had the same error, try adding "suffix="baf"" to the function, like:
loh <- readBAFExtractOutput ( path="all_BAF", sequencing.type="bulk", suffix="baf")

Hope it helps

**Comment by BilyanaStoilova** [comment]
Thank you very much @laloverdin, this indeed solved the problem with the loh. However, now when I run 
final.objects <- runCaSpER(object, removeCentromere=T, cytoband=cytoband, method="iterative")
It runs for quite some time and then gives me an error:
Performing recursive median filtering...
Performing HMM segmentation...
Processing cnv.scale:1 loh.scale:1...
Error in value[[jvseq[[jjj]]]] : subscript out of bounds
It seem there is still some problem with the loh, however this time I have no guess what the problem might be. Any ideas? I am using a test sample from just one patient, so my loh was generated with just 1 baf file - could this be an issue?
Thank you,
Bilyana

**Comment by iS4i4S** [comment]
@BilyanaStoilova  you are welcome.
Can you write the R code you used, so I can have a little more information?

THanks

**Comment by BilyanaStoilova** [comment]
@laloverdin, thank you very much! Here is all I did:
#generated normalized matrix from 10x data, where each gene count was divided to total UMI counts per cell and scaled by multiplying to 10,000.
#generate hg38 cytoband
cytoband <- read.delim("cytoBand.txt", header=F)
cytoband <- data.frame(V1=gsub("chr", "", cytoband[,1]), V2=cytoband[,2], V3=cytoband[,3], V4=substring(cytoband$V4, 1, 1), stringsAsFactors=F)
start <- do.call(rbind, lapply(split(cytoband$V2, paste0(cytoband$V1, cytoband$V4)), min))
end <- do.call(rbind, lapply(split(cytoband$V3, paste0(cytoband$V1, cytoband$V4)), max))
cytoband <- data.frame(V1=gsub("p", "", gsub("q", "", rownames(start))), V2=start, V3=end, V4=rownames(start), stringsAsFactors=F)
cytoband <- cytoband [as.vector(unlist(sapply(c(1:22, "X"), function(x) which(cytoband$V1 %in% x)))), ]
cytoband$V4[grep("q", cytoband$V4)] <- "q"
cytoband$V4[grep("p", cytoband$V4)] <- "p"
rownames(cytoband) <- NULL
cytoband_hg38 <- cytoband

#annotation
centromere <- read.table(file = "centromere.txt", sep = "\t", header = FALSE, stringsAsFactors = FALSE)
annotation <- generateAnnotation(id_type="hgnc_symbol", genes=rownames(matrix), ishg19=F, centromere = centromere)
matrix<- matrix[rownames(matrix) %in% annotation$Gene,]

#read BAFExtract output files
loh <- readBAFExtractOutput(path="./BAF", sequencing.type="bulk", suffix = "baf")
names(loh) <- gsub(".snp", "", names(loh))
loh.name.mapping <- annotations_file_Sample_1
loh.name.mapping$ID <- loh.name.mapping$Cell
loh.name.mapping$Cell <- "Sample_1"
colnames(loh.name.mapping) <- c("loh.name", "sample.name")

loh.name.mapping <- loh.name.mapping[loh.name.mapping$sample.name %in% annotations_file_Sample_1$Cell[annotations_file_Sample_1$ID != "Control"],]

control.sample.ids <- annotations_file_Sample_1$Cell[annotations_file_Sample_1$ID == "Control"]

#Creating casper object
object <- CreateCasperObject(raw.data=matrix,loh.name.mapping=loh.name.mapping, sequencing.type="single-cell", 
                             cnv.scale=3, loh.scale=3, matrix.type="normalized", expr.cutoff=4.5, log.transformed = F,
                             annotation=annotation, method="iterative", loh=loh, filter="median",  
                             control.sample.ids=control.sample.ids, cytoband=cytoband_hg38, genomeVersion = "hg38")
final.objects <- runCaSpER(object, removeCentromere=T, cytoband=cytoband_hg38, method="iterative")

Thank you very much for your help.

**Comment by akdess** [comment]
thanks a lot @laloverdin for the answer

**Comment by akdess** [comment]
@BilyanaStoilova for the second error: 

the "loh" list structure should only contain the samples in your loh.name.mapping. All the names(loh) should be in loh.name.mapping$loh.name. Hope it helps. I will update the code and tutorial to make it clear. Thanks a lot!

**Comment by iS4i4S** [comment]
@BilyanaStoilova  sorry for the delay on the second question.

@akdess you are very welcome.  I would like to take the opportunity for a question regarding the control samples since I did not find specific recommendations for this within the paper nor the documents. 

1.How does the number of control samples impacts the results?
2. Can the software run with no normal samples?
3.Can normal samples be tumoral samples which you know from genotyping that does not have CNA?

Thanks in advance

**Comment by BilyanaStoilova** [comment]
@akdess, thank you very much for the reply. After your message I looked at the loh data construction and managed to fix the problem. The whole problem was coming from the fact that I generated my baf file with suffix .baf according to the tutorial but I think it should have had a suffix .snp. That is why readBAFExtractOutput did not see any file before I specified the suffix and the line 
names(loh) <- gsub(".snp", "", names(loh))
was basically doing nothing and the names(loh) were not matching the loh.name.mapping$loh.name. So now after I changed it to
names(loh) <- gsub(".baf", "", names(loh))
runCaSpER is working as expected. 
Thank you

**Comment by akdess** [comment]
@BilyanaStoilova great I am glad to hear that it works. I should update the code and the tutorial to make it clear

**Comment by akdess** [comment]
@laloverdin thanks a lot for all your input. 

1.How does the number of control samples impacts the results?
If the control samples are not noisy then I would say even couple of them (around 1-3) would be enough.  We haven't done any formal analysis to study the optimal number of samples. But I have ran Casper with around n=3 control samples and the results were good. 
2. Can the software run with no normal samples?
We are working on this.
3.Can normal samples be tumoral samples which you know from genotyping that does not have CNA?
Yes, I have used chromosomally stable meningioma samples as control.

**Comment by iS4i4S** [comment]
@akdess thanks for answering my questions. I re-run your meningoma data using different number of samples, for example when running with only one control sample ("MN-69) and found that TPR stays at 95.45% but FPR worsens slightly from 0.61% to 3.33% (looking at chromosomical events). This helped me have an idea for my study and thought would be nice sharing.

I will look forward seeing updates in your software.

Thanks

**Comment by BilyanaStoilova** [comment]
@akdess, could I please ask you a few more questions? Does the plotLargeScaleEvent use all samples, including the control samples, and if so, is there a way to exclude the control samples from the plot? As far as I understand plotHeatmap uses this option. How should I do this for plotLargeScaleEvent?
I also noticed some discrepancies between finalChrMat (generated using extractLargeScaleEvents) and obj@large.scale.cnv.events. If I look at the finalChrMat
                               1p 1q 2p 2q 3p 3q 4p 4q 5p 5q 6p 6q 7p 7q 8p 8q 9p 9q 10p 10q 11p 11q 12p 12q 13p 13q 14p 14q 15p 15q
AAACCTGAGGAATGGA-1_  0  0  0  0  0  0  0  0 -1  0  1  0 -1 -1 -1  0  0  0   0   0   0   0   0   0   0   0   0   0   0   0
AAACCTGAGGCTAGCA-1_  1  0  0  0  0  0  0  0 -1  0  0  0 -1 -1  0  0  0  0   0   0   0   0   0   1   0   0   0   0   0   0
                               16p 16q 17p 17q 18p 18q 19p 19q 20p 20q 21p 21q 22p 22q
AAACCTGAGGAATGGA-1_   0   0   0   0  -1   0   0   0   0   0   0   0   0  -1
AAACCTGAGGCTAGCA-1_   0   0   0   0   0   0   0   0   0   0   0  -1   0   0
in the first cell I have a gain only at 6p, but if I look at obj@large.scale.cnv.events
                                                  LargeScaleAmp  FocalAmp LargeScaleAmpNum FocalAmpNum
AAACCTGAGGAATGGA-1_                      2q 6p 7q 9p 1p 1q 22q                4           3
AAACCTGAGGCTAGCA-1_                    1p 1q 12q 13q       19p                4           1
                                                             LargeScaleDel  FocalDel LargeScaleDelNum FocalDelNum
AAACCTGAGGAATGGA-1_             5p 7p 7q 8p 16p 16q 18p 20p 22q 6q 8q 13q                9           3
AAACCTGAGGCTAGCA-1_ 4p 5p 7p 7q 11q 15q 16p 16q 17q 20p 20q 21q 1p 8q 19q               12           3
It gives 4 LargeScaleAmp for the first cell (2q 6p 7q 9p). Could you please explain me why is that? Does plotLargeScaleEvent use obj@large.scale.cnv.events as an input? Thank you for clarifying these points for me.

**Comment by akdess** [comment]
thanks a lot @laloverdin!

**Comment by akdess** [comment]
Dear @BilyanaStoilova, 

You can modify the code in plotLargeScaleEvent. You can see the function if you type  plotLargeScaleEvent on the console. The first line is: 
    samps <- object@large.scale.cnv.events
You can only focus on the samples of interest by subsetting the data.frame with your samples of interest. You should add these lines to the function: 
samps <- samps[!(rownames(samps) %in%  object@control.sample.ids), ]

plotLargeScaleEvent only plots the results of one scale. 
extractLargeScaleEvents looks at all the scales and selects the events that are present in more than a defined threshold of scales (in demo scripts we used more than 75% of the scales). This produces more robust events with less false-positive rates. 

Hope it helps.

**Comment by BilyanaStoilova** [comment]
@akdess, thank you very much, as expected plotLargeScaleEvent results look much better after removing the control cells.

**Comment by akdess** [comment]
Great I am glad.
