### ISSUE TITLE
trouble using BAFEextract and/or casper on 10X data,

### ISSUE THREAD

**Issue by rLannes** [akdess/CaSpER#15]
Hi,

I am trying to use CaSpER but I run into trouble.

BAFExtract output one file, but the function of CaSpER readBAFEctractOuptut reads a directory.
If I put the output file in a directory it says that it doesn't found <my dir>//NA
My data are from a 10X run analysed with cellranger

here the Command line:

samtools view  <10XoutputDir>/<outs>/possorted_genome_bam.bam | ./BAFExtract -generate_compressed_pileup_per_SAM stdin hg38.list sample/ 50 0; /home/romain/Logiciel/BAFExtract/bin/BAFExtract -get_SNVs_per_pileup hg38.list sample/ hg38_fasta_pileups/ 20 4 0.1 out_baf

out_baf looks like this

1    14677    G    A    32    36
1    14686    A    T    8    68
1    135146    T    G    12    32

....

Then In R

loh <- readBAFExtractOutput ( path="out_baf/baf_file", sequencing.type = "bulk")
can't open file 'out_baf/NA'

Did I do something wrong? Should I need to extract a bam per cell before? then merging after?
Thank you in advance for your time and consideration,

Romain

**Comment by akdess** [comment]
Dear @rLannes, 
Thanks a lot for your interest!

I updated the readBAFExtractOutput function, you should specify the BAFExtract file extension as a parameter. If the output of BAFExtract is .baf files then you should say readBAFExtractOutput ( path="./meningioma_baf", sequencing.type="bulk", suffix="baf")
Hope it helps.

**Comment by rLannes** [comment]
Thank you the fix fixed the issue for me
