### ISSUE TITLE
Many bugs

### ISSUE THREAD

**Issue by ilona-grabowicz** [akdess/CaSpER#16]
Hi Akdess, 
I was trying to use your library, but it has so many bugs that I even can't go through the demo R files... And when I tried to run the analysis with my own files I got additional errors, from the lines which in your demos where commented but are necessary for my own files. If you install Casper from scratch and uncomment these lines you will find out how many things don't work :( I know that my message is quite vague but there were so many things not working that I would need to open numerous issues..
Best,
Ilona

**Comment by ozgunharmanci** [comment]
Dear Ilona, i am very sorry that you have the installation issues and having hard time running CaSpER. We are trying very hard to optimize the usability of CaSpER while optimizing and adding new features. 

We would like to go through the problems you are having and make sure you can run and interpret the results. I understand you encountered so many problems but, if you wish, we can go through all of them in this thread.

One of the major issues that we had to make sure is that the R has to be of specific version, I think it has to be version >3.4 (This is specified in the last tutorial). This could be on of the factors that may be causing problems.

Could you please kindly let us know the bugs you encountered? This could be in order you encountered them or in any other way. I really think there is a simple reason why you encountered so many bugs.

I apologize again for this.
Arif.
