### ISSUE TITLE
CNVs identified in control cells

### ISSUE THREAD

**Issue by lixin4306ren** [akdess/CaSpER#17]
Hi, thank you for providing such a useful tool for the community. 

I tried to use CaSpER on my 10x scRNA-seq tumor samples (skin cancer). Based on initial clustering and cell markers, I know some cell clusters are from normal cells (eg. immune cells) and then used them as control cells to identify CNVs during running CaSpER. However, I found CaSpER identified similar level of large-scale CNVs in both control cells and those potential tumor cells. 

I also checked those cells with very few or no CNVs by CaSpER and predicted them as "normal cells". I found these predicted "normal cells" actually came from all cell clusters including both control cells and tumor cells with similar proportions. How should I explain this result? Are there too many false positive/negative CNVs in the results? I filtered CNV results and had kept only CNVs with > 0.2 of all cells (common CNVs) and this did change the results. My aim of using CaSpER is to distinguish normal and normal cells in heterogeneous tumor samples, how should I run CaSpER properly. Thanks. 

Xin

**Comment by akdess** [comment]
Hi @lixin4306ren, 

Thanks a lot for your interest. 
I would recommend filtering the large scale CNV events present in less than 10% of cells. The algorithm might find false positives especially in amplifications. After filtering you can check if the results make sense by checking if the common skin cancer CNV events are detected or not. Hopefully this would make it better. You can also send me the output by email akdess at gmail com
