### ISSUE TITLE
Trouble shooting 

### ISSUE THREAD

**Issue by emauryg** [akdess/CaSpER#19]
There is a problem with CreatCasperObject

`object <- CreateCasperObject(raw.data=data_expr, loh.name.mapping= loh_raw.name.mapping, sequencing.type="bulk",
                            cnv.scale=3, loh.scale=3, matrix.type="normalized", expr.cutoff=1,annotation=annotation,
                            method="iterative", loh=loh_raw, filter="median",control.sample.ids="SRR10042621",cytoband=cytoband)`

With the following error:
'Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...): index 0 outside bounds
Traceback:

1. CreateCasperObject(raw.data = data_expr, loh.name.mapping = loh_raw.name.mapping, 
 .     sequencing.type = "bulk", cnv.scale = 3, loh.scale = 3, matrix.type = "normalized", 
 .     expr.cutoff = 1, annotation = annotation, method = "iterative", 
 .     loh = loh_raw, filter = "median", control.sample.ids = "", 
 .     cytoband = cytoband)
2. ProcessData(object)
3. PerformMedianFilterByChr(object)
4. apply(chr_data, 2, function(x) round(filter(MedianFilter(window.length + 
 .     1), x), digits = 2))
5. FUN(newX[, i], ...)
6. filter(MedianFilter(window.length + 1), x)
7. filter.MedianFilter(MedianFilter(window.length + 1), x)
8. runmed(x, filt$n)
9. smoothEnds(res, k = k)
10. med.odd(y[1L:j], j)
11. sort(x, partial = half)
12. sort.default(x, partial = half)
13. sort.int(x, na.last = na.last, decreasing = decreasing, ...)
'
This seems to be affecting the median filtering step. I have checked that the sample names and the loh names are the same, and followed the tutorial for yale meningioma/TCGA GBM for bulk rna sequencing.

**Comment by akdess** [comment]
Hi @emauryg, 

Thanks a lot for your interest! I am not sure about the problem. But I would be more than happy to resolve the issue if you send me the R object by email akdess at gmail com
