### ISSUE TITLE
Multiple warnings when creating casper object

### ISSUE THREAD

**Issue by JLTrincado** [akdess/CaSpER#2]
Dear authors,

first, congratulations for this really useful tool. 

I'm testing it on a Smart-seq dataset. At the time of creating the casper object, in single cell mode, I get the same warning several times:

# 1. Creating casper object
object <- CreateCasperObject(raw.data=merged_gene_exp2,loh.name.mapping=loh.name.mapping, sequencing.type="single-cell", 
  cnv.scale=3, loh.scale=3, annotation=annotation, method="iterative", loh=loh, 
  control.sample.ids="REF", cytoband=cytoband, genomeVersion = "hg38", log.transformed=TRUE, project = "T_ALL")

Changing 'k' to 5'k' is bigger than 'n'!  Changing 'k' to 3'k' is bigger than 'n'!  Changing 'k' to 3'k' is bigger than 'n'!  Changing 'k' to 15'k' is bigger than 'n'!  Changing 'k' to 23'k' is bigger than 'n'!  Changing 'k' to 3'k' is bigger than 'n'!  Changing 'k' to 9'k' is bigger than 'n'!  Changing 'k' to 7'k' is bigger than 'n'!  Changing 'k' to 7'k' is bigger than 'n'!  Changing 'k' to 11'k' is bigger than 'n'!  Changing 'k' to 3'k' is bigger than 'n'!  Changing 'k' to 11'k' is bigger than 'n'!  Changing 'k' to 1'k' is bigger than 'n'!  Changing 'k' to 1'k' is bigger than 'n'!  Changing 'k' to 5'k' is bigger than 'n'!  Changing 'k' to 19'k' is bigger than 'n'!  Changing 'k' to 15'k' is bigger than 'n'!  Changing 'k' to 11'k' is bigger than 'n'!  Changing 'k' to 7'k' is bigger than 'n'!  Changing 'k' to 13'k' is bigger than 'n'!  Changing 'k' to 9'k' is bigger than 'n'!  Changing 'k' to 7'k' is bigger than 'n'!  Changing 'k' to 5'k' is bigger than 'n'!  Changing 'k' to 3'k' is bigger than 'n'!  Changing 'k' to 3'k' is bigger than 'n'!  Changing 'k' to 15'k' is bigger than 'n'!  Changing 'k' to 23'k' is bigger than 'n'!  Changing 'k' to 3'k [...]

Why is this? Does it affect the results?

Thanks again.
Best.

**Comment by akdess** [comment]
Hi, that would be fine, it won't change the results. 

Thanks!
