### ISSUE TITLE
Error in DataFrame(..., check.names = FALSE) :    different row counts implied by arguments when performing runCaSpER(object, removeCentromere=T, cytoband=cytoband, method="iterative")

### ISSUE THREAD

**Issue by sjmeas** [akdess/CaSpER#20]
I am currently running into issues during "Step 2. Pairwise comparison of scales from BAF and expression signals" of your tutorial using a subset of my own data (yale_meningioma data works).

final.objects <- runCaSpER(object, removeCentromere=T, cytoband=cytoband, method="iterative")
Performing recursive median filtering...
Performing HMM segmentation...
Error in DataFrame(..., check.names = FALSE) : 
  different row counts implied by arguments
In addition: There were 50 or more warnings (use warnings() to see the first 50)

Traceback reveals the following;
traceback()
5: stop("different row counts implied by arguments")
4: DataFrame(..., check.names = FALSE)
3: GRanges(ranges = IRanges(start = annotation$start, end = annotation$end), 
       seqnames = annotation$cytoband, copy = data[, i], chr = annotation$cytoband, 
       space = annotation$cytoband)
2: PerformSegmentationWithHMM(object, cnv.scale = i, removeCentromere = T, 
       cytoband = cytoband)
1: runCaSpER(object, removeCentromere = T, cytoband = cytoband, 
       method = "iterative")

There appears to be a discrepancy between the lengths of data[,i] and annotation$cytoband. I believe this may be related to a problem originating from the CreateCasperObject function;

object <- CreateCasperObject(raw.data=newdata, loh.name.mapping=loh.name.mapping, sequencing.type="bulk", cnv.scale=3, loh.scale=3, matrix.type="normalized", expr.cutoff=4.5,
  annotation=annotation, method="iterative", loh=loh, filter="median",  
  control.sample.ids=control.sample.ids, cytoband=cytoband, genomeVersion= "hg38")
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In runmed(x, filt$n) : 'k' is bigger than 'n'!  Changing 'k' to 47
2: In runmed(x, filt$n) : 'k' is bigger than 'n'!  Changing 'k' to 47
3: In runmed(x, filt$n) : 'k' is bigger than 'n'!  Changing 'k' to 47
4: In runmed(x, filt$n) : 'k' is bigger than 'n'!  Changing 'k' to 47
5: In runmed(x, filt$n) : 'k' is bigger than 'n'!  Changing 'k' to 37
etc

I made sure that the centromere and cytoband data were correct for hg38 and compared them to your files on Github, in case the problem was initially with the generateAnnotation function.
If you have any ideas on how to proceed please let me know. Thank you.

**Comment by sjmeas** [comment]
This issue was fixed by creating a subset of data that matched the number of genes present in annotation (created by generateAnnotation).

**Comment by akdess** [comment]
Great thanks a lot, for letting us know.

**Comment by lifan18** [comment]
> This issue was fixed by creating a subset of data that matched the number of genes present in annotation (created by generateAnnotation).
Hello, thank you for your kind notes! I have the same Error in DataFrame. How did you create a subset of "data"? What the "data" for?

Thank you very much!
