### ISSUE TITLE
Gene expression matrix for bulk RNA-seq

### ISSUE THREAD

**Issue by evanwangx** [akdess/CaSpER#21]
Hello,

Could you explain the best method to generate the gene expression matrix for the bulk input?

In your tutorial, you specify that FPKM, TPM, or raw counts can be used to generate the gene expression matrix. Does the input have to be gene length normalized for best results? 

I'm using the DESeq2 workflow which produces it's own normalized counts and variance stabilization transformed counts, neither of which normalize for gene length. Would these be appropriate to use?

Thanks!

**Comment by akdess** [comment]
Hi @evanwangx, 

You can use the input you gave for Deseq2 for Casper. For example: 

dds <- DESeqDataSetFromMatrix(countData = countData,
                              colData = coldata,
                              design= ~ condition)

You can either use assays(dds)$counts or countData as input. But in CreateSeuratObject you have to set the following parameters: raw.data=countData ,  expr.cutoff = 1, matrix.type="raw"

We recently added the raw input option to Casper and I recommend you to try Casper with raw count matrix data input. 

Best,
Akdes

**Comment by dreammxy** [comment]
Hi! @akdess 
There are three RNA-seq datasets from different projects in my work. Should I normalize them before CaSpER? If needed, which methods do you suggest? sva, limma::removebatcheffct or others?
Thank you !

**Comment by akdess** [comment]
Hi @dreammxy , You can combine the raw read counts of these 3 datasets as one big matrix. You can give that matrix as an input to Casper.  No need to do batch effect correction. Hope it helps.

**Comment by dreammxy** [comment]
Hi,@akdess, I have combined raw counts of three datasets, then successfully created object, but when I run next step"runCaSpER", it reported error. I also tried example "yale_meningioma" data, it reported same error below:
> final.objects_yale <- runCaSpER(object_yale, removeCentromere=T, cytoband=cytoband, method="iterative")
Performing recursive median filtering...
Performing HMM segmentation...
Error in if (object@segments$size[i] > pair_arm_sizes * (1/3)) object@segments$event_scale[i] <- "large_scale" : 
  missing value where TRUE/FALSE needed
In addition: There were 15 warnings (use warnings() to see them)

**Comment by dreammxy** [comment]
Hi!@akdess, I wonder if there are differences between the results from one dataset and the results from combined big datasets. In other words, the bigger the datasets, the more accurate the results ?Thank you!

**Comment by akdess** [comment]
Hi @dreammxy, unfortunately we haven't run any accuracy analysis. I would assume with bigger datasets the results will be more accurate. I would appreciate if you let us know how it works on your datasets.

**Comment by dreammxy** [comment]
Hi@akdess, I have tried one dataset into Casper, and I have several problems.
1)This is the heatmap figure below, this is only shown the case samples, how could I sort the samples? I found in your script
"## sample plot orders
order.sampleNames <- c("MN-1171",  "MN-60835" ,"MN-1236" , "MN-1237" , "MN-1137" , "MN-1161" , "MN-60" ,   "MN-5" )"    
![heatmap](https://user-images.githubusercontent.com/38235922/87916773-78e6e080-caa6-11ea-8429-dbbd2f3764f3.png)
2)This is one sample from my data, and below is the GEandBAF figure, as you see the GE plot of all my data is upper than zero. Is something wrong with the normalization? 
![SRR3340816_GE_BAF](https://user-images.githubusercontent.com/38235922/87917292-54d7cf00-caa7-11ea-8114-80546ac7078e.png)
3) plotBAFInSeperatePages, when I used this command, 
Error in makeRectangleOverlay(start = max_num, end = max_num, dp = DisplayPars(lty = "dashed",  : 
  could not find function "makeRectangleOverlay"
Thank you  for your reply!

**Comment by akdess** [comment]
Dear @dreammxy, 
Thanks a lot for your interest!

1. You can change the code in plotHeatmap: 

   order.sampleNames # vector  for your ordered sample Names
  assignInNamespace(x = "draw_matrix", value = draw_matrix2, 
        ns = asNamespace("pheatmap"))
    assignInNamespace(x = "draw_colnames", value = "draw_colnames_45", 
        ns = asNamespace("pheatmap"))
    breaks <- seq(-2, 2, by = 0.2)
    color <- colorRampPalette(rev(brewer.pal(11, "RdYlBu")))(length(breaks))
    idx <- cumsum(table(object@annotation.filt$Chr)[as.character(1:22)])
    xlabel <- rep("", length(rownames(object@data)))
    half <- round(table(object@annotation.filt$Chr)[as.character(1:22)]/2)[-1]
    xpos <- c(half[1], (idx[-22] + half))
    xlabel[xpos] <- 1:22
    data <- log2(object@control.normalized.noiseRemoved[[cnv.scale]])
    pheatmap(t(data[, order.sampleNames]), cluster_cols = F, cluster_rows = F, gaps_col = idx, 
        color = color, breaks = breaks, labels_col = xlabel, 
        show_rownames = T, filename = "heatmap.png")
2. Looks like there is an event in chromosome 6. But I agree that GE plot looks weird. From the heatmap plot SRR3340816 shouldn't be all above 0, If you want I can look at your R object. 
3. You should install GenomeGraphs (https://www.bioconductor.org/packages//2.13/bioc/html/GenomeGraphs.html) for that function. 
Hope it helps! Thanks a lot for using our tool.

**Comment by dreammxy** [comment]
Dear @akdess，thanks a lot for your help. I still have no idea about the GE plot, and I have sent R object to you(akdess@gmail.com).
Thank you very much!

**Comment by garci1294** [comment]
Dear @akdess ,

Thank you for creating this excellent tool!

I am having the same issue as @dreammxy . I am working on the "yale_meningioma" tutorial (https://rpubs.com/akdes/673120) and I am also getting all of the expressions above 0 for the GE plot. This is for "yale_meningioma" data provided in the tutorial.

Has this issue been fixed, or is there a workaround?

Attached is the plot. 

Thank you,
Jesus

![MN-5_GE_BAF](https://user-images.githubusercontent.com/44952878/107148023-99796980-6916-11eb-9b07-49cdcebeed95.png)
