### ISSUE TITLE
R version 4.0.2

### ISSUE THREAD

**Issue by MasakoSuzuki** [akdess/CaSpER#23]
Hi,

It seems that some of the dependencies are not supported for R4.02. 
FYI, I am attaching the error messages I got when I run the "yale_meningioma" analysis.
Can you please help me to run this package on the current R version?

Thank you very much!

Masako
[R4_02.txt](https://github.com/akdess/CaSpER/files/5152990/R4_02.txt)

**Comment by akdess** [comment]
Hi @MasakoSuzuki, 

Thanks a lot for your interest. The reason for the error is GenomicRanges library. 

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("GenomicRanges")
library(GenomicRanges)

Thanks a lot,
Akdes

**Comment by MasakoSuzuki** [comment]
Hi Akdes,

Thank you so much for your quick response!

Unfortunately, I still got some errors and warnings at Visualization and runCaSpER steps.

Here are the error messages.

plotBAFInSeperatePages (loh =obj@loh.median.filtered.data, folderName="LOHPlotsSeperate") 
Error in makeRectangleOverlay(start = max_num, end = max_num, dp = DisplayPars(lty = "dashed",  : 
  could not find function "makeRectangleOverlay"

plotGEAllSamples (object=obj, fileName="GEAllSamples.pdf", cnv.scale=3) 
Error in data.frame(original = centered.control.normalized[, samples[i]],  : 
  no slot of name "control.normalized.visbound.noiseRemoved" for this object of class "casper"

FYI, I am attaching errors and warning with my sessioninfo.

Thank you so much in advance!

Masako

[CaSpER_03Sep2020.txt](https://github.com/akdess/CaSpER/files/5169095/CaSpER_03Sep2020.txt)

**Comment by akdess** [comment]
Hi @MasakoSuzuki, 
The error is because GenomeGraphs package is missing. We removed the dependency of GenomeGraphs in the updated Casper version. We will resolve this issue in the upcoming CaSpER version, I am very sorry about the issue.  You can install GenomeGraphs package https://bioconductor.riken.jp/packages/3.4/bioc/html/GenomeGraphs.html

**Comment by MasakoSuzuki** [comment]
Hi Akdes,

Thank you for your quick reply!
It seems the GenomeGraphs is not available for R version 4.0.2...
I will wait your updated version.

Best,

Masako
