### ISSUE TITLE
no "GRange" function runCaSpER error

### ISSUE THREAD

**Issue by siqi-zZ** [akdess/CaSpER#24]
> final.objects <- runCaSpER(object, removeCentromere=T, cytoband=cytoband, method="iterative")
Performing recursive median filtering...
Performing HMM segmentation...
Error in GRanges(ranges = IRanges(start = annotation$start, end = annotation$end),  : 
  没有"GRanges"这个函数

but I had load library(IRanges)

**Comment by akdess** [comment]
Hi @siqi-zZ , the error is about the GenomicRanges library. I updated the code to include package dependency. It should work now. 

Best,
Akdes

**Comment by siqi-zZ** [comment]
Hi Akdess,

Thank you for your  reply!  I found and solved yestoday by install "GenomicRanges". 👍 smile
                                                                                                                siqi

**Comment by siqi-zZ** [comment]
But I don't know why 
`> install.packages("~/Downloads/GenomicRanges_1.36.1.tgz", repos = NULL, type = .Platform$pkgType)
> library(GenomicRanges)
load package：GenomeInfoDb
> final.objects <- runCaSpER(object, removeCentromere=T, cytoband=cytoband, method="iterative")
Performing recursive median filtering...
Performing HMM segmentation...`



It take long time (more than 8h) but not finish 
It is normal?

**Comment by akdess** [comment]
Dear @siqi-zZ, I am sorry for my late reply. For big datasets it might take long. We will optimize the running time in our future updates.
