### ISSUE TITLE
Applicable to species other than human 

### ISSUE THREAD

**Issue by jiayiyiyao** [akdess/CaSpER#26]
Hi, thanks for the great tool. I am using it for detecting CNVs in bulk RNA-seq data from mouse samples. I noticed that the generateAnnotation() function has a parameter named "ishg19", and I got annotations that don't make sense if I input mouse gene list. I'm wondering that if this package is applicable to non human species such as mouse? 

Thanks in advance.

**Comment by abedkurdi** [comment]
Hi there, 
I have tested the package on `mouse data` too. I had to do some changes on `generateAnnotation` function to suit the `mouse` data. However, when invoking `runCaSpER`, it starts by `Performing recursive median filtering...` and then it continues with `Performing HMM segmentation...` and after few seconds it suddenly stops saying `Error in if (object@segments$size[i] > pair_arm_sizes * (1/3)) object@segments$event_scale[i] <- "large_scale" : 
  missing value where TRUE/FALSE needed` which clearly means the program is encountering `NULL`. I am suspecting a problem during `segmentation`, but not sure.

I have tested the package on the `tcga-gbm` dataset provided and it worked well.

I appreciate any suggestions,
Thank you.

**Comment by akdess** [comment]
Dear @jiayiyiyao and @abedkurdi, 

I am very sorry for the late reply. Here is the edited code for mouse https://github.com/akdess/CaSpER/blob/master/demo/CaSpER_for_Mouse.R The code should also resolve the error @abedkurdi 

Please let me know if that does not work. 

Best,
Akdes

**Comment by abedkurdi** [comment]
Thanks for your kind reply.
I did try your new code and `runCaSpER` ran successfully. However, when plotting the `heatmap` using the following:
`obj <- final.objects[[9]]`
`plotHeatmap(object=obj, fileName="heatmap.png",cnv.scale= 3, cluster_cols = F, cluster_rows = T, show_rownames = T, only_soi = T)` and it throws the following error: 
`Error in xlabel[xpos] <- 1:22 : NAs are not allowed in subscripted assignments`

So what do you suggest?
Thanks in advance.

**Comment by abedkurdi** [comment]
Thank you very much, your code worked really well!

**Comment by akdess** [comment]
Great, I am glad to hear that.
