### ISSUE TITLE
BAF does not go above 0.3 and hovers around 0.15

### ISSUE THREAD

**Issue by dstueckm** [akdess/CaSpER#27]
[LOH_plots_AllScales.pdf](https://github.com/akdess/CaSpER/files/5295580/LOH_plots_AllScales.pdf)

Hi there,

I managed to run your package on some 10X data, but have a question about the LOH plots that are produced.
Unlike in your tutorial (which I managed to follow successfully), the BAF never reaches 0.5, and the ylim of the plot is c(0,0,3). 

I was wondering:
a) If there was any biological explanation for why BAF would typically be 0.3 rather than 0.5 (or if this is just due to median filtering, and BAF is normally close to 0 or 0.5).
b) If you have any idea of why my plot looks this way, and how to resolve it. I'm happy to send the LOH data (or the BAFExtract output file).

Thanks in advance!

**Comment by akdess** [comment]
Hi @dstueckm I am not exactly sure why it looks that way. It might be a coverage issue. I am sorry about not being able to resolve your issue. Please let me know if you have any suggestions.
