### ISSUE TITLE
Differences in large-scale CNV's based on sample number?

### ISSUE THREAD

**Issue by jhb1980** [akdess/CaSpER#28]
Hi,

Exciting tool! I have a question regarding the large-scale CNV calculation from bulk RNA-seq data. Using the "full" sample set (6 diploid controls vs. 15 tumors) or a subset thereof (6 diploid controls vs. 10 of the tumors) produces in part different outcome estimates for the same sample (attaching the plots with a red highlight around a larger swatch of differences). 

Now I may have missed the explanation in the algorithm, but shouldn't within-sample estimates of RNA-seq and BAF remain identical and differences to "control" be preserved given that the same controls are used?

Thanks!

![2020-10-02 17_06_14-Window](https://user-images.githubusercontent.com/7883720/94939235-211b1b80-04d2-11eb-9fd1-75ca70b92d4a.png)

**Comment by akdess** [comment]
Hi @jhb1980, Thanks a lot for your interest! The algorithm estimates the deletion and amplification cutoffs from the data. So that is the issue here. I would look at the normalized expression signal heatmap to visualize and confirm the deletions and amplifications.

**Comment by AidenSb** [comment]
Hi @akdess,
May I know which parameters in CreateCasperObject, one can play around with for more stringent CNV calling? I do get a lot of CNV calls for my control samples and I was wondering if I can increase the stringency of the calls.

Thanks
