### ISSUE TITLE
Error in sCellGBM.R 

### ISSUE THREAD

**Issue by UmairSeemab** [akdess/CaSpER#33]
While running sCellGBM.R I got the error at line 16

> annotation <- generateAnnotation(id_type="ensembl_gene_id", genes=rownames(data), ishg19=T, centromere)
Error in UseMethod("filter_") : 
  no applicable method for 'filter_' applied to an object of class "c('tbl_SQLiteConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"

Could you help me to fix this issue? Thanks

**Comment by akdess** [comment]
Hi @UmairSeemab,

I am very sorry for the late reply. Unfortunately I am not getting this error. Let me know if you have any comments. 

Best,
Akdes

**Comment by akdess** [comment]
Hi @UmairSeemab, I updated the code in generateAnnotation, it should be fine now. Thanks a lot!
