### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by s849** [akdess/CaSpER#35]
Hi,

Thank you for developing CaSpER. I am trying to use this tool for my data but cannot install the dependencies. I get the following error:

sudo yum -y install libxml2-devel libcurl-devel libopenssl-devel openssl-devel
sudo: yum: command not found

I am working on a Mac. 

Any advice?

Thank you

**Comment by villegar** [comment]
`yum` (https://wiki.centos.org/PackageManagement/Yum) does not work with macOS. Instead, you should be using `brew` (https://brew.sh):
```bash
brew install libxml2
brew install curl-openssl
```

**Comment by akdess** [comment]
Thanks a lot @villegar for the reply.

**Comment by s849** [comment]
Thank you very much for your prompt replies!
