### ISSUE TITLE
control.normalized.visbound.noiseRemoved[[cnv.scale]][,samples[i]]  is null

### ISSUE THREAD

**Issue by zhangqi234** [akdess/CaSpER#36]
Hi,
Thank you for developing CaSpER. I am trying to  test meningioma data, but in the plotGEAllSamples function,I met this error:
> plotGEAllSamples (object=obj, fileName="GEAllSamples.pdf", cnv.scale=3)
Error in data.frame(original = centered.control.normalized[, samples[i]],  :
  arguments imply differing number of rows: 24045, 0
> object@control.normalized.visbound.noiseRemoved[[cnv.scale]][,samples[i]]
NULL

**Comment by akdess** [comment]
Dear @zhangqi234, 

Thanks a lot for your interest! I am very sorry for the late reply. 

I forgot to update plotGEAllSamples function in the latest version of Casper. I have corrected the error. It should work now. Please let me know if you still have any problems. 

Thanks a lot for letting me know.

**Comment by zhangqi234** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thanks very much!
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                zhangqi2019m
                            
                    
                        
                            
                                    zhangqi2019m@big.ac.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 11/19/2020 13:19，Akdes Serin Harmanci<notifications@github.com> wrote： 



Dear @zhangqi234,
Thanks a lot for your interest! I am very sorry for the late reply.
I forgot to update plotGEAllSamples function in the latest version of Casper. I have corrected the error. It should work now. Please let me know if you still have any problems.
Thanks a lot for letting me know.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
