### ISSUE TITLE
Using CaSpER to identify malignant cells based on CNVs

### ISSUE THREAD

**Issue by avln24** [akdess/CaSpER#37]
Hi there,

Thank you for this tool.

I am interested in using CaSpER to identify CNVs in cancer scRNA-seq data. We want to classify malignant and non-malignant cells based on the inferred CNV patterns. I have successfully applied CaSpER to one dataset, and it was able to identify and visualize CNV patterns, but i'm not sure how to classify cells as either malignant or non-malignant based on the outputs of CaSpER. Is there a certain object I should use? Do you have any suggestions as how I could do this using the results of CaSpER? 

Thank you!

**Comment by akdess** [comment]
Dear @avln24

Thanks a lot for your interest!

That is a very important question and not very easy to answer. You can first cluster the cells using Seurat and select non-malignant cells using known non-malignant cell marker genes. You expect to see the non-malignant cells to cluster together in TSNE or UMAP plot. Additionally the CaSpER large scale CNV calls should be neutral in non-malignant cells.   

You can generate TSNE plot using RunTSNE function in Seurat and using FeaturePlot function in Seurat you can see the expression of non-malignant cell marker. 

If you don't know any non-malignant cell marker, you can predict those cells by first clustering the cells using Seurat and annotating the TSNE or UMAP cluster as non-malignant if large scale CNV calls generated by Casper are all (or almost all, considering the false calls) neutral. 

Hope it helps. Please let me know if you have any further questions.
Best,
Akdes
