### ISSUE TITLE
generating genoMat

### ISSUE THREAD

**Issue by garci1294** [akdess/CaSpER#39]
Hello @akdess ,

Thank you for this great tool. 

I am working with bulk RNA-seq data, and I am confused about generating the 'genoMat.' I can create the finalChrMat using the 'extractLargeScaleEvents' function. I also noticed the 'genoMat' has a similar format; however, I can't find how to generate it from the manual or tutorials.

Any suggestion is appreciated.

Thank you so much,
Jesus

**Comment by lmasatti** [comment]
Sorry @garci1294 did you fixet it? How did you manage it?

**Comment by Junedays** [comment]
I am also curious about this issue. When i Checked the help file, i noticed that genoMat was explained to be 
"large scale events identified from genotyping array represented as matrix. Rows indicates samples (cells) whereas columns indicates chromosome arms". I guess may be this is not inferred from codes, but should be from actual genotyping array data.
