### ISSUE TITLE
Creating loh object from BAFExtract output

### ISSUE THREAD

**Issue by joeymays** [akdess/CaSpER#4]
Hi, 

I have a question concerning the expected output for BAFExtract. I'm running the following line in R after running the BAFExtract code below:

`loh <- readBAFExtractOutput ( path=."/placenta_BAF_output", sequencing.type="single-cell")`

`samtools view ./cellranger3/outs/*.bam | ../BAFExtract -generate_compressed_pileup_per_SAM stdin ./GRCh38.list ./placenta_BAF_output/ 50 0`

`../BAFExtract -get_SNVs_per_pileup ./GRCh38.list ./placenta_BAF_output/ ./BAFExtract_genome/ 20 4 0.1 ./placenta_6220.baf`

I'm getting a "cannot open file" error from the R function; it seems to be expecting files in the output directory with a `.snp` tag in the filename. Should there be other files output from the `-get_SNVs_per_pileup` in addition to the `.baf` file?

**Comment by olferievm** [comment]
It is not working for me. I generated output files with BAFExtract based on the example provided. There are no .snp type files. The command below can't work as there is no such type of files. Could you explain from were .snp files should be obtained?

loh <- readBAFExtractOutput ( path="./meningioma_baf\\", sequencing.type="bulk")
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file './meningioma_baf\/NA': No such file or directory

**Comment by peter-yufan-zeng** [comment]
I am running into the same issues as mentioned above. 
@akdess  any way to fix this issue? Thanks in advance!

**Comment by akdess** [comment]
@peter-yufan-zeng @olferievm @joeymays 
I am very sorry for my late reply.  I have updated the readBAFExtractOutput function, you should specify the BAFExtract file extension as a parameter.  If the output of BAFExtract is .baf files then you should say readBAFExtractOutput ( path="./meningioma_baf\", sequencing.type="bulk", suffix="baf")
Hope it helps.
