### ISSUE TITLE
plotHeatmap() saves the plot in the working directory and not at the specified path

### ISSUE THREAD

**Issue by ftucos** [akdess/CaSpER#46]
plotHeatmap() function was ignoring the file name parameter and exporting everything in the working directory as "heatmap.png".
I sent you a pull request fixing this bug

**Comment by mmfalco** [comment]
In plotHeatmap10x() function, also doesn't take into account some other arguments such as `show_rownames`. It should be great if some color sidebar could be added in the plot to add additional annotations.

**Comment by cstubben** [comment]
Both plotHeatmap and plotHeatmap10x fail to pass options like fileName, show_rownames, cluster_cols, cluster_rows to the pheatmap function (and maybe add dots ... for additional arguments).

**Comment by akdess** [comment]
Thanks a lot @ftucos, @mmfalco and @cstubben for reporting this issue!
