### ISSUE TITLE
Error when using readBAFExtractOutput

### ISSUE THREAD

**Issue by moutazhelal** [akdess/CaSpER#48]
Hi thank you for such a great package,

I have recently come across your package and I am interested in using it to explore CNVs in scRNA-seq. 
I  am trying to read the BAF files using the following : 
`loh <- readBAFExtractOutput ( path="D:/CASPER/", sequencing.type="scRNA") `
but I always get an error 

> Error in file(file, "rt") : cannot open the connection
> In addition: Warning message:
> In file(file, "rt") :
>   cannot open file 'D:/CASPER//NA': No such file or directory

I will really appreciate your help

 R version 4.0.3

**Comment by jefferyUstc** [comment]
I have read the source code, a param named `suffix` with `snp` as default is the source of error. change this parameter, then it works.

```
readBAFExtractOutput <- function(path, sequencing.type = "bulk", suffix = "snp") {
    
    files <- list.files(path)
    files <- files[grep(paste0(".", suffix,"$"), files)]
    
    
    loh <- list()
    for (i in 1:length(files)) {
        maf <- read.table(file.path(path, files[i]), header = F, stringsAsFactor = F)
        maf <- data.frame(chr = maf[, 1], position = maf[, 2], alt = maf[, 5], ref = maf[, 6] - maf[, 5], coverage = maf[, 
            6], baf = maf[, 5]/maf[, 6], dev = abs(as.numeric(maf[, 5]/maf[, 6]) - 0.5))
        maf <- maf[order(maf$position), ]
        idx = unlist(as.vector((sapply(1:22, function(x) as.vector(unlist(which(as.character(maf$chr) == x)))))))
        maf <- maf[idx, ]
        j <- 0.2
        if (sequencing.type == "bulk") 
            maf <- maf[maf$baf > j & maf$baf < (1 - j), ]
        if (sequencing.type == "single-cell") 
            maf <- maf[maf$baf > j, ]
        loh[[i]] <- maf
    }
    
    names(loh) <- files
    return(loh)
}
```

**Comment by akdess** [comment]
Thanks a lot @jefferyUstc and @moutazhelal for bringing up this issue!
