### ISSUE TITLE
Running CaSpER with single cell data

### ISSUE THREAD

**Issue by NienkeMekkes** [akdess/CaSpER#5]
Dear Authors,

Thank you for creating the CaSpER tool. I have a question about running CaSpER on single cell data sets. 

For the example dataset, I could not run two vizualisation/info-metrics lines:

- `plotSCellCNVTree`
error messages: `Metric: 'jaccard'; comparing: 70 vectors.
arguments 'show.output.on.console', 'minimized' and 'invisible' are for Windows only
sh: C:UsersaharmanciDownloadsphylip-3.695phylip-3.695exe/fitch: No such file or directory
error in running commandempty character string`. I tried the phylip R package as well. 

and

-  `all.summary <- getDiffExprGenes(final.objects,  sampleName="MGH31", chrs=c("5q", "14q"), event.type=c(1, -1))`
error message: `Zero sample variances detected, have been offset away from zero[1] "Calculating differential expression..."`

Do you perhaps have any advice on these problems?

----------------------------------------
Furthermore, I tried to use CaSpER with a publicly available dataset, in my case sc data from 10X: https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/pbmc_1k_v3
I tried to create the `loh` object, but ran into trouble. I used the BAM file provided by 10x, but could not reproduce the example output. This problem is the same as this: https://github.com/akdess/CaSpER/issues/4 , when running samtools view and readBAFExtractOutput. My only generated output file is the .baf file, and no .snp files

 `samtools view <bam_file> | ./BAFExtract -generate_compressed_pileup_per_SAM stdin <genome_list> <sample_dir> 50 0; ./BAFExtract -get_SNVs_per_pileup  <genome_list> <sample_dir> <genome_fasta_pileup_dir> 20 4 0.1 <output_baf_file>`

and 

`loh <- readBAFExtractOutput ( path="./meningioma_baf\\", sequencing.type="bulk")
names(loh) <- gsub(".snp", "", names(loh))`

----------------------------------------------------
As a side, for the example set, I found the following warnings:
When running `object <- CreateCasperObject(raw.data=data, ..., )`:
- `Changing 'k' to 5'k' is bigger than 'n'! Changing 'k' to 3'k' is bigger than 'n'! Changing 'k' to 3'k' is bigger than 'n'! Changing 'k' to 15'k' is bigger than 'n'!`

- `See IMPORTANT NOTE in ?RangedData  RangedData objects are deprecated. Please migrate your code to use GRanges or GRangesList objects instead.`

When running `results <- extractMUAndCooccurence (finalChrMat, loh, loh.name.mapping)`:

- `NAs introduced by coercion`

When running `plotMUAndCooccurence (results)`:

- `length of NULL cannot be changed`

I've read we can ignore the top one, is this true for the other warnings as well?

Thank you for your time,
Nienke

**Comment by akdess** [comment]
@NienkeMekkes thanks a lot for your interest. 

I have updated the code for RangedData  deprecation issue. 

_My only generated output file is the .baf file, and no .snp files_
The output should be baf files you are right, I have updated the code.

_getDiffExprGenes_ error should be because of having no differentially expressed genes. 

_plotSCellCNVTree_ requires another software to be installed. I will make it more clear. Thanks a lot!
