### ISSUE TITLE
generateAnnotation issue

### ISSUE THREAD

**Issue by ccruizm** [akdess/CaSpER#6]
Hello!

I am really excited to test your tool to detect CNV in scRNA data. I have my own 10x data sets and have tried to run the pipeline following your vignette. However I have a problem trying to generate the annotation of my genes. I have used both `ensembl_gene_id` and `hgnc_symbol` as options for id_type in the function `generateAnnotation`, but always have the same error:

```
Error in getBM(filters = id_type, attributes = c(id_type, "hgnc_symbol", : Invalid attribute(s): entrezgene 
Please use the function 'listAttributes' to get valid attribute names
Traceback:

1. generateAnnotation(id_type = "hgnc_symbol", genes = rownames(data_1258), 
 .     ishg19 = T, centromere)
2. getBM(filters = id_type, attributes = c(id_type, "hgnc_symbol", 
 .     "entrezgene", "chromosome_name", "start_position", "end_position", 
 .     "band"), values = genes, mart = mart)
3. stop(paste("Invalid attribute(s):", paste(attributes[invalid], 
 .     collapse = ", "), "\nPlease use the function 'listAttributes' to get valid attribute names"))
```

What do you think might be the issue here? I am using the correct ensembl or gene symbol id. I also tried loading the Yale_meningioma dataset and didn't work neither. 

Thanks in advance for your help!

**Comment by akdess** [comment]
Hi @ccruizm, Sorry for my late reply. Can you list the top values for  rownames(data_1258)?
