### ISSUE TITLE
Annotation file for hg38

### ISSUE THREAD

**Issue by Troyee13** [akdess/CaSpER#63]
Hello,
I have my own set of bulk RNA seq BAM files analysed with hg38 genome. Please elaborate on how to generate an annotation file for hg38 with Caspe. Thanks

**Comment by Troyee13** [comment]
I have figured it out. No issue.

**Comment by lifan18** [comment]
> I have figured it out. No issue.

Hi Troyee, I have the same issue to generate a right annotation file for hg38. I used the following code to make this file, however, it cannot be used properly in the later process.

`annotation <- generateAnnotation(id_type="hgnc_symbol", genes=rownames(scRNA@assays$RNA@data), centromere=centromere, ishg19 = T)`

Then, errors came in `CreateCasperObject`
`
There were 50 or more warnings (use warnings() to see the first 50)
`
and in `final.objects`
`final.objects <- runCaSpER(object, removeCentromere=T, cytoband=cytoband, method="iterative")
Performing recursive median filtering...
Performing HMM segmentation...
Error in DataFrame(..., check.names = FALSE) :
  different row counts implied by arguments
`

Did you get any solution?

Thank you!
